'use client';
import {useEffect,useMemo,useReducer,useRef,useState} from 'react';
import {flushSync} from 'react-dom';
import {Waves,ArrowUpRight,ArrowRight,ArrowLeft,BookOpen,Wallet,Info,ChevronDown,Check,FlaskConical,RotateCcw,Play,Pause,ExternalLink,SlidersHorizontal,Plus,MousePointer2,CheckCircle2,Coins} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {ASSETS,SCENARIOS,DEFAULT_CONFIG,initialState,reducer,simulate,validateConfig,type Config,type Scenario,type Point} from '@/lib/simulator';

const money=(n:number,d=2)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:d,maximumFractionDigits:d}).format(n);
const num=(n:number,d=4)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:d}).format(n);
const pct=(n:number,d=2)=>`${(n*100).toFixed(d)}%`;
const signed=(n:number)=>`${n>=-0.005?'+':'−'}${money(Math.abs(n))}`;
function Coin({symbol,small=false}:{symbol:string;small?:boolean}){const a=ASSETS.find(a=>a.symbol===symbol);return <span className={`coin ${a?.tone||'usd'} ${small?'small':''}`}>{a?.letter||'$'}</span>}
function InfoBox({children}:{children:React.ReactNode}){return <div className="explainer"><Info size={18}/><p>{children}</p></div>}
function RangeGraph({lower,upper,price=100}:{lower:number;upper:number;price?:number}){
 const lo=Math.min(50,lower*.8),hi=Math.max(160,Math.min(upper*1.1,12000));
 const y=(p:number)=>174-(p-lo)/(hi-lo)*142;
 const prices=Array.from({length:41},(_,i)=>100+Math.sin(i*.38)*9+i*.18);
 return <svg className="range-graph" viewBox="0 0 520 210" role="img" aria-label={`当前价格 ${price} 美元，选定工作区间 ${lower} 至 ${upper} 美元。蓝线为示意价格，不是历史行情。`}>
 <defs><linearGradient id="rangeTint" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#ffb6df" stopOpacity=".23"/><stop offset="1" stopColor="#ffb6df" stopOpacity=".07"/></linearGradient></defs>
 {[0,1,2,3].map(i=><line key={i} x1="15" x2="456" y1={30+i*47} y2={30+i*47} stroke="#f2eef3" strokeDasharray="3 5"/>)}
 <rect x="15" y={y(upper)} width="441" height={Math.max(1,y(lower)-y(upper))} fill="url(#rangeTint)"/>
 <line x1="15" x2="456" y1={y(upper)} y2={y(upper)} stroke="#fa80c3" strokeDasharray="4 4"/><line x1="15" x2="456" y1={y(lower)} y2={y(lower)} stroke="#fa80c3" strokeDasharray="4 4"/>
 <polyline points={prices.map((p,i)=>`${15+i*11},${y(p)}`).join(' ')} fill="none" stroke="#bab6ca" strokeWidth="2"/>
 <line x1="15" x2="456" y1={y(price)} y2={y(price)} stroke="#fb1698" strokeWidth="1.5"/>
 <circle cx="232" cy={y(price)} r="5" fill="#fb1698" stroke="white" strokeWidth="3"/>
 <text x="464" y={y(upper)+4} fill="#c66a9e" fontSize="12">{num(upper,0)}</text><text x="464" y={y(lower)+4} fill="#c66a9e" fontSize="12">{num(lower,0)}</text>
 <text x="15" y="202" fill="#a299a7" fontSize="12">粉色区域：你的流动性工作区间</text><text x="387" y="202" fill="#a299a7" fontSize="12">示意路径</text>
 </svg>
}
function BalanceGraph({data}:{data:Point[]}){
 const max=Math.max(...data.map(p=>Math.max(p.totalValue,p.holdValue)))*1.03,min=Math.min(...data.map(p=>Math.min(p.totalValue,p.holdValue)))*.97;
 const x=(d:number)=>48+d/30*655,y=(v:number)=>212-(v-min)/(max-min||1)*177;
 const points=(key:'totalValue'|'holdValue')=>data.map(p=>`${x(p.day)},${y(p[key])}`).join(' ');
 const last=data.at(-1)!;
 return <svg className="balance-graph" viewBox="0 0 740 255" role="img" aria-label={`第 ${last.day} 天，提供流动性含手续费价值 ${money(last.totalValue)}，原样持有 ${money(last.holdValue)}。`}>
 {[0,1,2,3].map(i=>{const v=min+(max-min)*i/3;return <g key={i}><line x1="48" x2="705" y1={y(v)} y2={y(v)} stroke="#eeeaf0" strokeDasharray="3 5"/><text x="40" y={y(v)+4} textAnchor="end" fontSize="11" fill="#a299a7">{num(v,0)}</text></g>})}
 {[0,10,20,30].map(d=><text key={d} x={x(d)} y="243" textAnchor="middle" fontSize="12" fill="#9d939f">第 {d} 天</text>)}
 <polyline points={points('holdValue')} stroke="#bbb6c6" strokeWidth="2" strokeDasharray="5 5" fill="none"/>
 <polyline points={points('totalValue')} stroke="#fc0b92" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" fill="none"/>
 <circle cx={x(last.day)} cy={y(last.totalValue)} r="5" fill="#fc0b92" stroke="white" strokeWidth="3"/>
 </svg>
}
function Assumptions(){return <details className="assumptions"><summary><SlidersHorizontal size={14}/> 模拟假设与计算口径<ChevronDown size={14}/></summary><div>
 <p>采用 Uniswap v3 集中流动性数学；资产价格统一从 $100 起算。币对、区间、成交量、费率及竞争资金均为教学设定，未读取真实池或行情。</p>
 <p>USDG 恒定按 $1 计算。虚拟美元按起始价格准备两种资产；不计兑换、Gas、滑点、税费、分红与拆股。股份换算乘数保持不变。</p>
 <p>日内价格在相邻日期间线性变化，成交量按时间均匀分布；只有路径处在区间内的部分计费。其他活跃流动性保持不变，对应起始价 $100、区间 $1–$10,000、投入 $100,000 的固定参考头寸。</p>
 <p>模拟手续费按获得时价值记为美元，不模拟手续费代币后续涨跌，不自动复投。协议抽成可调整，与真实池是否启用无关。窄区间不会自动提高真实成交量。</p>
 <p>总盈亏 = 仓位价值 + 累计手续费 − 初始本金。相对持有差额只用于比较，不再重复扣除。价格区间采用连续值，未模拟 tick 舍入；不构成真实交易报价。</p>
 </div></details>}
const lessons=[
 {q:'我究竟把钱放到了哪里？',a:'你把两种资产存进智能合约管理的池子，供交易者兑换。例如有人用 USDG 买股票代币，池子里的股票代币会减少，USDG 会增加。你的仓位也会跟着改变。'},
 {q:'收益是谁付给我的？',a:'交易者为兑换支付手续费。同一时刻能参与交易的流动性一起分配这笔费用；你的活跃流动性份额越高，分到的比例越大。部分池子还会先扣除协议抽成。没有成交，就没有这部分收入。'},
 {q:'为什么要设置价格区间？',a:'区间决定你的资产在哪些价格上参与兑换。相同金额放在更窄的区间，会形成更集中的流动性，区间内的分成可能更高；代价是价格更容易越界，越界期间不会获得新手续费。'},
 {q:'价格越界，资产会消失吗？',a:'不会。涨到上界时，仓位中的股票代币已逐渐换成 USDG；跌到下界时，USDG 已逐渐换成股票代币。出区间后数量固定，手续费暂停。跌破下界后，股票代币仍可能继续跌价。价格回到区间，仓位会重新参与交易。'},
 {q:'“无常损失”到底在比较什么？',a:'把同样的两种币原样拿着，与把它们放入池子后的价值比较。不含手续费时，做市仓位可能比原样持有的价值少，这个差额通常叫无常损失。它不等于账户一定亏钱，也不能再从仓位价值里扣一次。价格回到起点且区间不变时，这个差额可消失；价格也可能不再回来。'},
 {q:'赚到了手续费，就代表赚钱了吗？',a:'不一定。例如资产下跌造成的损失，可能大于赚到的手续费。上涨时，仓位逐渐卖出股票代币，也可能跑输原样持有。请同时看“总盈亏”和“相对原样持有差额”，手续费只是其中一部分。'},
 {q:'Robinhood 股票代币等于直接持有股票吗？',a:'新版 Robinhood Stock Tokens 是 Robinhood Assets (Jersey) Limited 发行的代币化债务证券，提供标的证券的经济敞口，并不赋予标的公司的股东权利。它与第一代 Classic Stock Tokens 不同，真实可用性以地区条件和官方规则为准。'},
];

export default function Home(){
 const [state,dispatch]=useReducer(reducer,initialState);
 const [review,setReview]=useState(false),[withdrawOpen,setWithdrawOpen]=useState(false),[resetOpen,setResetOpen]=useState(false),[tradeDemo,setTradeDemo]=useState(false),[playing,setPlaying]=useState(false),[quiz,setQuiz]=useState<number|null>(null);
 const ref=useRef(state);ref.current=state;
 const c=state.config,position=state.position;
 const calc=validateConfig(c,Number.MAX_VALUE)?DEFAULT_CONFIG:c;
 const start=useMemo(()=>simulate(calc,'sideways',0)[0],[calc]);
 const resultData=useMemo(()=>position?simulate(position.config,position.scenario,position.day):null,[position]);
 const result=resultData?.at(-1);
 const previousPrice=resultData?.at(-2)?.price??100;
 const eligible=start.active;const dailyFee=eligible?calc.dailyVolume*calc.feeRate*(1-calc.protocolShare)*start.share:0;
 const errors=validateConfig(c,state.balance);
 const stepError=state.step===2?errors:validateConfig({...c,deposit:10},Number.MAX_VALUE);
 const field=(n:number)=>Number.isFinite(n)?n:'';
 const patch=(p:Partial<Config>)=>dispatch({type:'configure',patch:p});
 const setScenario=(s:Scenario)=>{setPlaying(false);dispatch({type:'scenario',scenario:s})};
 useEffect(()=>{if(!playing||!position||position.closed)return;const timer=setInterval(()=>{const s=ref.current;if(!s.position||s.position.day>=30){setPlaying(false);return;}dispatch({type:'day',day:s.position.day+1})},550);return ()=>clearInterval(timer)},[playing,position?.closed]);
 useEffect(()=>{if(position?.day===30||state.view!=='portfolio')setPlaying(false)},[position?.day,state.view]);
 useEffect(()=>{
  const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>Promise<void>|void}}).modelContext;if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  const snapshot=()=>{const s=ref.current;const p=s.position;return {view:s.view,config:s.config,virtualBalance:s.balance,position:p,result:p?simulate(p.config,p.scenario,p.day).at(-1):null}};
  const register=(tool:unknown)=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}};
  register({name:'get_liquidity_lab_state',description:'Read the current teaching simulation and virtual wallet. No real funds.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>snapshot()});
  register({name:'configure_liquidity_lab',description:'Set teaching inputs and open the deposit review step. Does not create a position or transact.',inputSchema:{type:'object',properties:{deposit:{type:'number',minimum:10},lower:{type:'number',minimum:1},upper:{type:'number',maximum:10000},dailyVolume:{type:'number',minimum:0,maximum:10000000}},additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('Expected settings object');const patch=input as Record<string,unknown>;if(Object.keys(patch).some(k=>!['deposit','lower','upper','dailyVolume'].includes(k))||Object.values(patch).some(v=>typeof v!=='number'))throw new Error('Invalid settings');if(ref.current.position&&!ref.current.position.closed)throw new Error('Withdraw the existing simulated position first.');const next={...ref.current.config,...patch};const err=validateConfig(next,ref.current.balance);if(err)throw new Error(err);flushSync(()=>{dispatch({type:'configure',patch});dispatch({type:'step',step:2});dispatch({type:'view',view:'setup'})});return snapshot()}});
  register({name:'run_liquidity_lab_scenario',description:'Create a virtual position from the configured inputs if none is open, then run a selected 0–30 day scenario and show its results. Uses virtual money only. Does not withdraw.',inputSchema:{type:'object',properties:{scenario:{type:'string',enum:SCENARIOS.map(s=>s.id)},day:{type:'integer',minimum:0,maximum:30}},required:['scenario','day'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const v=input as {scenario:Scenario;day:number};if(!v||Object.keys(v).some(k=>!['scenario','day'].includes(k))||!SCENARIOS.some(s=>s.id===v.scenario)||!Number.isInteger(v.day)||v.day<0||v.day>30)throw new Error('Invalid scenario or day');const s=ref.current;if(!s.position||s.position.closed){const err=validateConfig(s.config,s.balance);if(err)throw new Error(err)}flushSync(()=>{if(!s.position||s.position.closed)dispatch({type:'create'});dispatch({type:'scenario',scenario:v.scenario});dispatch({type:'day',day:v.day});dispatch({type:'view',view:'portfolio'});setPlaying(false)});return snapshot()}});
  return ()=>lifecycle.abort();
 },[]);
 return <div className="site">
 <header className="topbar"><a className="brand" href="/" onClick={e=>{e.preventDefault();dispatch({type:'view',view:'setup'})}}><Waves/><span>流动性实验室<span className="brand-en">Liquidity Lab</span></span></a><nav aria-label="主导航">{[{id:'setup',name:'模拟提供流动性'},{id:'portfolio',name:'我的仓位'},{id:'learn',name:'机制小课堂'}].map(n=><button key={n.id} aria-current={state.view===n.id?'page':undefined} className={state.view===n.id?'nav-active':''} onClick={()=>dispatch({type:'view',view:n.id as typeof state.view})}>{n.name}{n.id==='portfolio'&&position&&!position.closed&&<i className="nav-dot"/>}</button>)}</nav><span className="sandbox"><FlaskConical size={15}/>教学模拟</span><button className="wallet" onClick={()=>setResetOpen(true)} aria-label={`虚拟余额 ${money(state.balance)}，重置实验`}><Wallet size={17}/>{money(state.balance,0)}<span>虚拟余额</span></button></header>
 <main className="workspace"><div className="eyebrow"><span/>LEARN BY DOING</div><div className="page-title"><div><h1>{state.view==='setup'?'让资产流动起来':state.view==='portfolio'?'你的第一笔流动性':'把机制，真的弄明白'}<span>。</span></h1><p>{state.view==='setup'?'用一笔虚拟资金，弄懂流动性如何带来收益。':state.view==='portfolio'?'换一种行情，看一笔投入会发生什么。':'从一次兑换开始，理解收益与风险从哪里来。'}</p></div><span className="safe-label"><FlaskConical size={16}/>无需钱包 · 无真实交易</span></div>
 {state.view==='setup'&&<div className="work-grid"><section className="panel setup-panel"><div className="stepper" aria-label="创建流动性步骤">{['选择资产','设置区间','存入资金'].map((t,i)=><button key={t} onClick={()=>dispatch({type:'step',step:i})} className={i===state.step?'current':i<state.step?'complete':''} aria-current={i===state.step?'step':undefined}><span>{i<state.step?<Check size={15}/>:i+1}</span>{t}</button>)}</div><div className="panel-body">
 {state.step===0&&<><div className="section-heading"><h2>选择你的资产组合</h2><span>第 1 步 / 3</span></div><p className="muted">把两种资产放进同一个池子，让交易者在它们之间兑换。</p><div className="chain-pill"><i/>Robinhood Chain <span>· 教学情景</span></div><div className="asset-card"><Coin symbol={c.asset}/><div><label className="sr-only" htmlFor="asset">股票代币</label><select id="asset" value={c.asset} onChange={e=>patch({asset:e.target.value})}>{ASSETS.map(a=><option key={a.symbol} value={a.symbol}>{a.symbol} · {a.name}</option>)}</select><span>Robinhood Stock Token · 示例币对</span></div><ChevronDown size={18}/></div><div className="pair-plus">+</div><div className="asset-card"><Coin symbol="USDG"/><div><strong>USDG</strong><span>Global Dollar · 假设 1 USDG = $1</span></div></div><div className="fee-heading"><label htmlFor="fee">交易手续费率</label><span>只用于本次模拟</span></div><div className="fee-options" id="fee" role="group" aria-label="手续费档位">{[.0005,.003,.01].map(f=><button key={f} className={c.feeRate===f?'selected':''} onClick={()=>patch({feeRate:f})} aria-pressed={c.feeRate===f}>{pct(f)}{f===.003&&<span>默认教学档</span>}</button>)}</div><InfoBox>有人用你的资产完成兑换，就会支付手续费。你按活跃流动性份额，与其他提供者分这笔钱。</InfoBox></>}
 {state.step===1&&<><div className="section-heading"><h2>让资金在哪个区间工作？</h2><span>第 2 步 / 3</span></div><p className="muted">价格在区间内，才会参与兑换并分到手续费。</p><div className="price-heading"><span>{c.asset} 教学起始价</span><strong>$100.00 <small>USDG / 枚</small></strong></div><div className="range-presets" role="group" aria-label="价格区间预设">{[{name:'窄区间',a:95,b:105,note:'±5%'},{name:'宽区间',a:80,b:120,note:'±20%'},{name:'很宽区间',a:1,b:10000,note:'$1–10,000'}].map(r=><button key={r.name} className={c.lower===r.a&&c.upper===r.b?'selected':''} onClick={()=>patch({lower:r.a,upper:r.b})}><strong>{r.name}</strong><span>{r.note}</span></button>)}</div><RangeGraph lower={calc.lower} upper={calc.upper}/><div className="range-inputs"><label>最低价格<div><span>$</span><input aria-label="最低价格" type="number" min="1" max="9999" step="1" value={field(c.lower)} onChange={e=>patch({lower:e.target.value===''?NaN:Number(e.target.value)})}/></div></label><label>最高价格<div><span>$</span><input aria-label="最高价格" type="number" min="1" max="10000" step="1" value={field(c.upper)} onChange={e=>patch({upper:e.target.value===''?NaN:Number(e.target.value)})}/></div></label></div><InfoBox>{eligible?'区间越窄，同样资金在区间内的分成可能越多；价格也更容易跑出去。试试窄区间，再模拟持续上涨。':`起始价已在区间外：你将只存入 ${calc.price0>=calc.upper?'USDG':c.asset}，起初不赚手续费。价格进入区间后才开始参与交易。`}</InfoBox></>}
 {state.step===2&&<><div className="section-heading"><h2>投入多少虚拟资金？</h2><span>第 3 步 / 3</span></div><p className="muted">系统按起始价格和区间，帮你准备两种资产。</p><div className="deposit-card"><label htmlFor="deposit">模拟投入总金额</label><div className="amount-field"><span>$</span><input id="deposit" type="number" min="10" max={state.balance} value={field(c.deposit)} onChange={e=>patch({deposit:e.target.value===''?NaN:Number(e.target.value)})}/><span>USD</span></div><div className="deposit-foot"><span>可用虚拟余额 {money(state.balance,0)}</span><button onClick={()=>patch({deposit:state.balance})}>全部</button></div></div><div className="amount-presets">{[500,1000,5000].map(n=><button key={n} aria-pressed={c.deposit===n} className={c.deposit===n?'selected':''} onClick={()=>patch({deposit:n})}>{money(n,0)}</button>)}</div><div className="allocation"><div><Coin small symbol={c.asset}/><span>{c.asset}<small>按教学价准备</small></span><strong>{num(start.x)}<small>{money(start.x*calc.price0)}</small></strong></div><div><Coin small symbol="USDG"/><span>USDG<small>美元稳定币</small></span><strong>{num(start.y,2)}<small>{money(start.y)}</small></strong></div><div className="allocation-bar"><span style={{width:`${start.x*calc.price0/calc.deposit*100}%`}}/></div><p>配比随区间变化，不必各占一半。</p></div><InfoBox>这一步只使用虚拟余额，不会连接钱包或发起交易。创建仓位后，你可以拖动时间，观察 30 天的变化。</InfoBox></>}
 {stepError&&<p role="alert" className="error-message">{stepError}</p>}
 {state.step<2?<Button className="primary" disabled={!!stepError} onClick={()=>dispatch({type:'step',step:state.step+1})}>继续：{state.step===0?'设置价格区间':'存入虚拟资金'}<ArrowRight size={18}/></Button>:<Button className="primary" disabled={!!errors||(!!position&&!position.closed)} onClick={()=>setReview(true)}>预览模拟仓位<ArrowRight size={18}/></Button>}
 {position&&!position.closed&&<button className="text-button center" onClick={()=>dispatch({type:'view',view:'portfolio'})}>已有进行中的实验，查看我的仓位 <ArrowUpRight size={14}/></button>}
 {state.step>0&&<button className="back-button" onClick={()=>dispatch({type:'step',step:state.step-1})}><ArrowLeft size={14}/>返回上一步</button>}
 </div></section><aside className="side-stack"><section className="panel preview-card"><div className="overline">收益从哪里来</div><h2>{state.step===0?<>每一笔交易，<br/>都有你的参与<span>。</span></>:<>你的资金，<br/>开始为交易服务<span>。</span></>}</h2><div className="flow"><div><span className="flow-icon"><ArrowUpRight/></span>交易者</div><ArrowRight size={18}/><div><span className="flow-icon pink"><Waves/></span>流动性池</div><ArrowRight size={18}/><div><span className="flow-icon"><Wallet/></span>你</div></div><div className="example"><span>按当前设定 · 完整在区间内的 1 天</span><strong>{money(dailyFee)} <span>模拟手续费</span></strong><p>{eligible?'随区间、成交量与资金份额实时计算。':'起始价在区间外，当前不能获得手续费。'}</p></div><dl className="breakdown"><div><dt>每日模拟成交量</dt><dd>{money(calc.dailyVolume,0)}</dd></div><div><dt>分给全部 LP 的费率</dt><dd>{pct(calc.feeRate*(1-calc.protocolShare),4)}</dd></div><div><dt>你的活跃流动性份额</dt><dd>{eligible?pct(start.share):'0%（未激活）'}</dd></div></dl><button className="trade-demo-button" onClick={()=>setTradeDemo(!tradeDemo)} aria-expanded={tradeDemo}><MousePointer2 size={14}/>{tradeDemo?'收起分账演示':'看一笔 $1,000 交易怎么分'}<ChevronDown size={14}/></button>{tradeDemo&&<div className="trade-demo"><p>交易者支付 <b>{money(1000*calc.feeRate)}</b></p><p>扣除协议抽成 <b>{money(1000*calc.feeRate*calc.protocolShare)}</b></p><p>所有活跃 LP 共分 <b>{money(1000*calc.feeRate*(1-calc.protocolShare))}</b></p><p className="pink-text">你获得 <b>{money(eligible?1000*calc.feeRate*(1-calc.protocolShare)*start.share:0,4)}</b></p><small>独立演示，不计入模拟账户。</small></div>}</section><section className="lesson-card"><BookOpen size={21}/><div><strong>手续费收入 ≠ 最终盈利</strong><p>资产价格也在变化。窄区间可能提高分成，也可能让你更早停止赚取手续费。</p><button className="text-button" onClick={()=>dispatch({type:'view',view:'learn'})}>先花一分钟了解机制 <ArrowUpRight size={13}/></button></div></section><details className="parameters"><summary><SlidersHorizontal size={14}/>调整教学参数<ChevronDown size={14}/></summary><div><label>每日模拟成交量（USD）<input type="number" min="0" max="10000000" value={field(c.dailyVolume)} onChange={e=>patch({dailyVolume:e.target.value===''?NaN:Number(e.target.value)})}/></label><label>协议抽成（占交易手续费）<select value={c.protocolShare} onChange={e=>patch({protocolShare:Number(e.target.value)})}><option value={1/6}>16.67% · 教学假设</option><option value={0}>0% · 假设未启用</option></select></label><p>各档位沿用相同的模拟成交量；真实交易量会受费用和竞争影响。</p></div></details><span className="caption">所有价格、成交量和收益均为教学假设。<br/>模拟结果不代表实际收益。</span></aside></div>}
 {state.view==='portfolio'&&(!position||!result)?<section className="panel empty-state"><span className="empty-icon"><Waves size={35}/></span><h2>你的实验，从第一笔存入开始。</h2><p>选择股票代币、设定价格区间，用虚拟资金体验做市。</p><Button className="primary" onClick={()=>dispatch({type:'view',view:'setup'})}>创建模拟仓位<Plus size={17}/></Button></section>:null}
 {state.view==='portfolio'&&position&&result&&resultData&&<div className="portfolio"><div className="position-header"><div className="pair-title"><div className="double-coins"><Coin symbol={position.config.asset}/><Coin symbol="USDG"/></div><div><h2>{position.config.asset} / USDG</h2><span>Robinhood Chain · 集中流动性教学</span></div></div><span className={`status-pill ${position.closed?'closed':result.active?'active':'inactive'}`}><i/>{position.closed?'已取出':result.active?'区间内 · 参与交易':'区间外 · 手续费暂停'}</span></div>
 {state.message&&<div className="notice" role="status"><CheckCircle2 size={17}/>{state.message}</div>}
 <section className="metrics" aria-label="模拟收益结果"><div><span>{position.closed?'本次取出总额':'仓位总价值'} <small>含手续费</small></span><strong>{money(result.totalValue)}</strong><p>初始投入 {money(position.config.deposit,0)}</p></div><div><span>累计模拟手续费</span><strong className="positive">+{money(result.fees)}</strong><p>单独累积 · 未自动复投</p></div><div><span>模拟总盈亏</span><strong className={result.pnl>=0?'positive':'negative'}>{signed(result.pnl)}</strong><p>{pct(result.pnl/position.config.deposit)} · 未计交易成本</p></div></section>
 <div className="portfolio-grid"><div className="portfolio-main"><section className="panel chart-panel"><div className="section-heading"><h2>把时间往前推一推</h2><span className="day-badge">DAY {String(position.day).padStart(2,'0')}</span></div><p className="muted">选择一条假设行情，比较提供流动性与原样持有。</p><div className="scenario-tabs" role="group" aria-label="模拟行情">{SCENARIOS.map(s=><button key={s.id} className={position.scenario===s.id?'selected':''} disabled={position.closed} onClick={()=>setScenario(s.id)} aria-pressed={position.scenario===s.id}>{s.name}</button>)}</div><div className="chart-legend"><span><i className="pink-line"/>提供流动性（含手续费）</span><span><i/>原样持有两种资产</span></div><BalanceGraph data={resultData}/><div className="timeline"><button className="play-button" disabled={position.closed||position.day===30} aria-label={playing?'暂停模拟':'自动播放 30 天模拟'} onClick={()=>setPlaying(!playing)}>{playing?<Pause size={18}/>:<Play size={18}/>}</button><input type="range" min="0" max="30" step="1" value={position.day} disabled={position.closed} aria-label="模拟天数" onChange={e=>{setPlaying(false);dispatch({type:'day',day:Number(e.target.value)})}}/><span>{position.day} / 30 天</span></div><div className="day-controls"><button disabled={position.closed} onClick={()=>{setPlaying(false);dispatch({type:'day',day:0})}}><RotateCcw size={13}/>回到起点</button>{[1,7,30].map(d=><button key={d} disabled={position.closed||position.day===30} onClick={()=>{setPlaying(false);dispatch({type:'day',day:d===30?30:Math.min(30,position.day+d)})}}>{d===30?'直接看第 30 天':`前进 ${d} 天`}</button>)}</div><p className="scenario-note">{SCENARIOS.find(s=>s.id===position.scenario)?.description} 切换行情和时间会重新计算同一笔投入，余额在取出时结算。</p></section>
 <section className="panel comparison"><div className="section-heading"><h2>这笔钱，真的多赚了吗？</h2><Info size={17}/></div><div className="compare-row"><div><span>如果原样持有</span><p>最初两种资产的数量保持不变</p></div><strong>{money(result.holdValue)}</strong></div><div className="compare-row"><div><span>放进流动性池</span><p>当前资产价值 + 累计手续费</p></div><strong>{money(result.totalValue)}</strong></div><div className={`compare-result ${result.vsHold>=0?'good':'bad'}`}><span>{result.vsHold>=-.005?'比原样持有多':'比原样持有少'}</span><strong>{money(Math.abs(result.vsHold))}</strong></div><details className="compare-details"><summary>展开盈亏分解 <ChevronDown size={14}/></summary><div><p><span>仓位价值变化</span><b>{signed(result.positionValue-position.config.deposit)}</b></p><p><span>加上手续费</span><b className="positive">+{money(result.fees)}</b></p><p><span>合计：相对本金的总盈亏</span><b>{signed(result.pnl)}</b></p><p><span>不含费，相对原样持有差额</span><b>{signed(result.impermanentLoss)}</b></p><small>最后一项通常称为无常损失，已经体现在仓位价值里，不再重复扣减。</small></div></details></section></div>
 <aside className="side-stack"><section className="panel holdings"><div className="section-heading"><h2>{position.closed?'取出时的资产快照':'资产正在怎样变化'}</h2></div><div className="current-price"><span>{position.config.asset} {position.closed?'结算教学价':'当前教学价'}</span><strong>{money(result.price)}<small className={result.price>=100?'positive':'negative'}>{pct(result.price/100-1,1)}</small></strong></div><div className="holdings-row"><Coin small symbol={position.config.asset}/><div><strong>{position.config.asset}</strong><span>{num(result.x)} 枚</span></div><b>{money(result.x*result.price)}</b></div><div className="holdings-row"><Coin small symbol="USDG"/><div><strong>USDG</strong><span>{num(result.y,2)} 枚</span></div><b>{money(result.y)}</b></div><div className="allocation-bar"><span style={{width:`${result.positionValue?result.x*result.price/result.positionValue*100:0}%`}}/></div><div className="holding-explanation">{position.closed?'资产和手续费已全部取出，当前流动性仓位为零。上方数量为取出时的快照，价格变化不会重新激活已结束的仓位。':result.price>=position.config.upper?'价格已超过上界，仓位里的股票代币已全部换成 USDG。继续上涨时，仓位不会再跟随股票上涨。':result.price<position.config.lower?'价格已跌破下界，仓位里的 USDG 已全部换成股票代币。继续下跌时，仓位仍会损失价值。':position.day===0?'这是存入时按区间准备的两种资产。推动时间后，配比会随价格变化。':Math.abs(result.price-100)<1e-8?'当前价格回到起始水平；在固定区间、未复投的模型中，资产配比也回到起点。':result.price>previousPrice?'本日价格上涨，仓位逐渐卖出股票代币，换入更多 USDG。':result.price<previousPrice?'本日价格下跌，仓位逐渐用 USDG 换入更多股票代币。':'本日价格保持不变，仓位配比不变。'}</div><dl className="breakdown"><div><dt>工作区间</dt><dd>{money(position.config.lower,0)} – {money(position.config.upper,0)}</dd></div><div><dt>实际在区间内</dt><dd>{num(result.activeDays,1)} / {position.day} 天</dd></div><div><dt>当前活跃份额</dt><dd>{!position.closed&&result.active?pct(result.share):'0%'}</dd></div></dl>{!position.closed?<Button className="primary" onClick={()=>{setPlaying(false);setWithdrawOpen(true)}}>模拟取出全部<ArrowUpRight size={17}/></Button>:<Button className="primary" onClick={()=>{patch({deposit:Math.max(10,Math.min(c.deposit,state.balance))});dispatch({type:'view',view:'setup'});dispatch({type:'step',step:1})}}>再试一个价格区间<ArrowRight size={17}/></Button>}<p className="caption inline-caption">{position.closed?`已折算返还 ${money(position.settlement!)} 虚拟美元`:'取出时按当前教学价折算，手续费一并返还。'}</p></section><section className="lesson-card"><BookOpen size={21}/><div><strong>{position.closed?'本次实验已结算':result.fees>0&&result.pnl<0?'收到手续费，仍可能亏损':result.fees>0&&result.vsHold<0?'赚到手续费，也可能跑输持有':!result.active?'越界以后，手续费暂停':'同一笔投入，多试几种行情'}</strong><p>{position.closed?'本次结果已冻结。可以重新设置区间开启下一次实验，或点击虚拟余额重置为 $10,000。':result.fees>0&&result.pnl<0?'资产下跌的损失超过手续费。总盈亏一栏体现两者相加的结果。':result.fees>0&&result.vsHold<0?'做市会改变两种资产的数量。资产配比变化造成的差额，可能大于收到的手续费。':!result.active?'你仍持有资产，旧手续费也仍然保留。价格重新进入区间后，会恢复参与交易。':'试试持续上涨与持续下跌。相同的费率和本金，不会自动带来相同的结果。'}</p></div></section></aside></div></div>}
 {state.view==='learn'&&<div className="learn-grid"><div><section className="panel lesson-intro"><span className="lesson-number">01 / 核心机制</span><h2>你提供资产，<br/>交易者支付手续费。</h2><p>把流动性池想成一个自动兑换柜台。你提供柜台里的两种资产，别人来兑换；每次兑换收取的手续费，按参与交易的份额分给提供者。</p><div className="learning-equation"><div><Coins/><b>成交量</b></div><span>×</span><div><SlidersHorizontal/><b>LP 有效费率</b></div><span>×</span><div><Waves/><b>你的活跃份额</b></div><span>=</span><div className="pink-text"><Wallet/><b>手续费</b></div></div><p className="small-note">这条式子在每段区间内的成交上计算。手续费之外，资产的数量和价格也会变化。</p></section><div className="lesson-list">{lessons.map((l,i)=><details key={l.q} className="panel" open={i===0?true:undefined}><summary><span className="lesson-index">{String(i+1).padStart(2,'0')}</span>{l.q}<Plus size={17}/></summary><p>{l.a}</p></details>)}</div></div><aside className="side-stack"><section className="panel quiz"><span className="overline">一分钟小测</span><h2>价格涨出了你的上界，<br/>会发生什么？</h2>{['继续赚手续费，资产配比不变','仓位全为 USDG，新增手续费暂停','资产被自动清零'].map((a,i)=><button key={a} className={quiz===i?i===1?'correct':'incorrect':''} onClick={()=>setQuiz(i)}>{String.fromCharCode(65+i)}<span>{a}</span>{quiz===i&&i===1&&<Check size={16}/>}</button>)}{quiz!==null&&<p role="status" className={quiz===1?'positive':'negative'}>{quiz===1?'答对了。价格回到区间后，仓位还可以重新参与兑换。':'再想想：上涨时，池子会逐渐卖出股票代币，换进 USDG。越界只会停止赚新手续费。'}</p>}</section><Button className="primary" onClick={()=>dispatch({type:'view',view:'setup'})}>现在亲手试一次<ArrowRight size={18}/></Button><section className="sources"><strong>资料与学习来源</strong><p>机制核对：2026 年 9 月 8 日</p><a href="https://blog.uniswap.org/robinhood-chain-is-live" target="_blank" rel="noreferrer">Uniswap × Robinhood Chain<ExternalLink size={13}/></a><a href="https://developers.uniswap.org/docs/get-started/concepts/liquidity-providers/concentrated-liquidity" target="_blank" rel="noreferrer">Uniswap 集中流动性<ExternalLink size={13}/></a><a href="https://developers.uniswap.org/docs/get-started/concepts/fees" target="_blank" rel="noreferrer">手续费与协议抽成<ExternalLink size={13}/></a><a href="https://blog.uniswap.org/uniswap-v3-math-primer-2" target="_blank" rel="noreferrer">Uniswap 仓位计算<ExternalLink size={13}/></a><a href="https://robinhood.com/rhj/stocktokens/" target="_blank" rel="noreferrer">Robinhood 股票代币说明<ExternalLink size={13}/></a><a href="https://www.youtube.com/watch?v=UhIvDWY3pCA&t=4s" target="_blank" rel="noreferrer">打开学习视频<ExternalLink size={13}/></a><small>视频参数尚未核实；本站参数由教学设定。</small></section></aside></div>}
 <Assumptions/><footer><span>一个可以放心试错的 DeFi 学习空间</span><span>独立教学项目 · 非 Uniswap / Robinhood 官方产品</span></footer>
 </main>
 <Dialog open={review} onOpenChange={setReview}><DialogContent className="review-modal"><span className="modal-icon"><Waves size={29}/></span><DialogTitle>确认你的模拟仓位</DialogTitle><DialogDescription>以下操作仅扣减本次实验中的虚拟余额。</DialogDescription><div className="modal-pair"><Coin small symbol={c.asset}/><Coin small symbol="USDG"/><strong>{c.asset} / USDG</strong></div><dl className="review-list"><div><dt>模拟投入</dt><dd>{money(calc.deposit)}</dd></div><div><dt>价格区间</dt><dd>{money(calc.lower,0)} – {money(calc.upper,0)}</dd></div><div><dt>{c.asset} / USDG 数量</dt><dd>{num(start.x)} / {num(start.y,2)}</dd></div><div><dt>交易手续费率</dt><dd>{pct(calc.feeRate)}</dd></div><div><dt>分给全部 LP 的费率</dt><dd>{pct(calc.feeRate*(1-calc.protocolShare),4)}</dd></div></dl><InfoBox>资产配比会随价格变化。手续费收入不保证弥补资产价格波动造成的损失。</InfoBox><Button className="primary" disabled={!!errors} onClick={()=>{dispatch({type:'create'});setReview(false)}}>确认，创建模拟仓位<Check size={17}/></Button></DialogContent></Dialog>
 <Dialog open={withdrawOpen} onOpenChange={setWithdrawOpen}><DialogContent className="review-modal"><span className="modal-icon"><Wallet size={27}/></span><DialogTitle>结束这次模拟并取出</DialogTitle><DialogDescription>仓位资产和累计手续费一起按当前教学价折算为虚拟美元。取出后，本次结果会保留。</DialogDescription><div className="withdraw-value">{money(result?.totalValue||0)}<span>返还虚拟余额 · 未计交易成本</span></div><Button className="primary" onClick={()=>{dispatch({type:'withdraw'});setWithdrawOpen(false)}}>确认模拟取出<ArrowUpRight size={17}/></Button></DialogContent></Dialog>
 <Dialog open={resetOpen} onOpenChange={setResetOpen}><DialogContent className="review-modal"><span className="modal-icon"><RotateCcw size={27}/></span><DialogTitle>重新开始这个实验？</DialogTitle><DialogDescription>清除当前模拟仓位与结果，虚拟余额恢复为 $10,000。本次实验只在当前页面保留，刷新也会重置。</DialogDescription><div className="withdraw-value">{money(state.balance)}<span>当前可用虚拟余额</span></div><Button className="primary" onClick={()=>{setPlaying(false);dispatch({type:'reset'});setResetOpen(false)}}>重置为 $10,000<RotateCcw size={16}/></Button></DialogContent></Dialog>
 </div>
}
